/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PayBillRouteImport } from './routes/pay-bill'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResellerRouteImport } from './routes/_authenticated.reseller'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated.customer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedResellerIndexRouteImport } from './routes/_authenticated.reseller.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as PayBillReceiptReceiptNoRouteImport } from './routes/pay-bill.receipt.$receiptNo'
import { Route as AuthenticatedResellerSupportRouteImport } from './routes/_authenticated.reseller.support'
import { Route as AuthenticatedResellerSmsRouteImport } from './routes/_authenticated.reseller.sms'
import { Route as AuthenticatedResellerReportsRouteImport } from './routes/_authenticated.reseller.reports'
import { Route as AuthenticatedResellerPackagesRouteImport } from './routes/_authenticated.reseller.packages'
import { Route as AuthenticatedResellerCustomersRouteImport } from './routes/_authenticated.reseller.customers'
import { Route as AuthenticatedResellerCustomerSearchRouteImport } from './routes/_authenticated.reseller.customer-search'
import { Route as AuthenticatedResellerAccountsHistoryRouteImport } from './routes/_authenticated.reseller.accounts-history'
import { Route as AuthenticatedResellerAccountsRouteImport } from './routes/_authenticated.reseller.accounts'
import { Route as AuthenticatedAdminZonesRouteImport } from './routes/_authenticated.admin.zones'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated.admin.tickets'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated.admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated.admin.packages'
import { Route as AuthenticatedAdminOltRouteImport } from './routes/_authenticated.admin.olt'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated.admin.notices'
import { Route as AuthenticatedAdminMikrotikRouteImport } from './routes/_authenticated.admin.mikrotik'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'
import { Route as AuthenticatedAdminBillsRouteImport } from './routes/_authenticated.admin.bills'
import { Route as AuthenticatedAdminAppearanceRouteImport } from './routes/_authenticated.admin.appearance'
import { Route as AuthenticatedAdminAddressRouteImport } from './routes/_authenticated.admin.address'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated.admin.accounts'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated.admin.access'
import { Route as AuthenticatedAdminResellersIndexRouteImport } from './routes/_authenticated.admin.resellers.index'
import { Route as AuthenticatedAdminHrIndexRouteImport } from './routes/_authenticated.admin.hr.index'
import { Route as AuthenticatedAdminCallCenterIndexRouteImport } from './routes/_authenticated.admin.call-center.index'
import { Route as ApiPublicCronRunRouteImport } from './routes/api/public/cron/run'
import { Route as AuthenticatedAdminResellersAddRouteImport } from './routes/_authenticated.admin.resellers.add'
import { Route as AuthenticatedAdminResellersAccessRouteImport } from './routes/_authenticated.admin.resellers.access'
import { Route as AuthenticatedAdminReportsAddressRouteImport } from './routes/_authenticated.admin.reports.address'
import { Route as AuthenticatedAdminHrSalaryPoliciesRouteImport } from './routes/_authenticated.admin.hr.salary-policies'
import { Route as AuthenticatedAdminHrReportsRouteImport } from './routes/_authenticated.admin.hr.reports'
import { Route as AuthenticatedAdminHrPayrollRouteImport } from './routes/_authenticated.admin.hr.payroll'
import { Route as AuthenticatedAdminHrLeaveRouteImport } from './routes/_authenticated.admin.hr.leave'
import { Route as AuthenticatedAdminHrEmployeesRouteImport } from './routes/_authenticated.admin.hr.employees'
import { Route as AuthenticatedAdminHrAttendanceRouteImport } from './routes/_authenticated.admin.hr.attendance'
import { Route as AuthenticatedAdminHrAdvanceSalaryRouteImport } from './routes/_authenticated.admin.hr.advance-salary'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated.admin.customers_.$id'
import { Route as AuthenticatedAdminCallCenterVoiceTemplatesRouteImport } from './routes/_authenticated.admin.call-center.voice-templates'
import { Route as AuthenticatedAdminCallCenterSipNumbersRouteImport } from './routes/_authenticated.admin.call-center.sip-numbers'
import { Route as AuthenticatedAdminCallCenterReportsRouteImport } from './routes/_authenticated.admin.call-center.reports'
import { Route as AuthenticatedAdminCallCenterIpPhonesRouteImport } from './routes/_authenticated.admin.call-center.ip-phones'
import { Route as AuthenticatedAdminCallCenterFollowUpsRouteImport } from './routes/_authenticated.admin.call-center.follow-ups'
import { Route as AuthenticatedAdminCallCenterCallLogsRouteImport } from './routes/_authenticated.admin.call-center.call-logs'
import { Route as AuthenticatedAdminCallCenterAutoVoiceSmsRouteImport } from './routes/_authenticated.admin.call-center.auto-voice-sms'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillRoute = PayBillRouteImport.update({
  id: '/pay-bill',
  path: '/pay-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResellerRoute = AuthenticatedResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResellerIndexRoute =
  AuthenticatedResellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PayBillReceiptReceiptNoRoute = PayBillReceiptReceiptNoRouteImport.update({
  id: '/receipt/$receiptNo',
  path: '/receipt/$receiptNo',
  getParentRoute: () => PayBillRoute,
} as any)
const AuthenticatedResellerSupportRoute =
  AuthenticatedResellerSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerSmsRoute =
  AuthenticatedResellerSmsRouteImport.update({
    id: '/sms',
    path: '/sms',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerReportsRoute =
  AuthenticatedResellerReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerPackagesRoute =
  AuthenticatedResellerPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerCustomersRoute =
  AuthenticatedResellerCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerCustomerSearchRoute =
  AuthenticatedResellerCustomerSearchRouteImport.update({
    id: '/customer-search',
    path: '/customer-search',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerAccountsHistoryRoute =
  AuthenticatedResellerAccountsHistoryRouteImport.update({
    id: '/accounts-history',
    path: '/accounts-history',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedResellerAccountsRoute =
  AuthenticatedResellerAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedResellerRoute,
  } as any)
const AuthenticatedAdminZonesRoute = AuthenticatedAdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOltRoute = AuthenticatedAdminOltRouteImport.update({
  id: '/olt',
  path: '/olt',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMikrotikRoute =
  AuthenticatedAdminMikrotikRouteImport.update({
    id: '/mikrotik',
    path: '/mikrotik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillsRoute = AuthenticatedAdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAppearanceRoute =
  AuthenticatedAdminAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAddressRoute =
  AuthenticatedAdminAddressRouteImport.update({
    id: '/address',
    path: '/address',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResellersIndexRoute =
  AuthenticatedAdminResellersIndexRouteImport.update({
    id: '/resellers/',
    path: '/resellers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrIndexRoute =
  AuthenticatedAdminHrIndexRouteImport.update({
    id: '/hr/',
    path: '/hr/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterIndexRoute =
  AuthenticatedAdminCallCenterIndexRouteImport.update({
    id: '/call-center/',
    path: '/call-center/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronRunRoute = ApiPublicCronRunRouteImport.update({
  id: '/api/public/cron/run',
  path: '/api/public/cron/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminResellersAddRoute =
  AuthenticatedAdminResellersAddRouteImport.update({
    id: '/resellers/add',
    path: '/resellers/add',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResellersAccessRoute =
  AuthenticatedAdminResellersAccessRouteImport.update({
    id: '/resellers/access',
    path: '/resellers/access',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsAddressRoute =
  AuthenticatedAdminReportsAddressRouteImport.update({
    id: '/reports/address',
    path: '/reports/address',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrSalaryPoliciesRoute =
  AuthenticatedAdminHrSalaryPoliciesRouteImport.update({
    id: '/hr/salary-policies',
    path: '/hr/salary-policies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrReportsRoute =
  AuthenticatedAdminHrReportsRouteImport.update({
    id: '/hr/reports',
    path: '/hr/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrPayrollRoute =
  AuthenticatedAdminHrPayrollRouteImport.update({
    id: '/hr/payroll',
    path: '/hr/payroll',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrLeaveRoute =
  AuthenticatedAdminHrLeaveRouteImport.update({
    id: '/hr/leave',
    path: '/hr/leave',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrEmployeesRoute =
  AuthenticatedAdminHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrAttendanceRoute =
  AuthenticatedAdminHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrAdvanceSalaryRoute =
  AuthenticatedAdminHrAdvanceSalaryRouteImport.update({
    id: '/hr/advance-salary',
    path: '/hr/advance-salary',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers_/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterVoiceTemplatesRoute =
  AuthenticatedAdminCallCenterVoiceTemplatesRouteImport.update({
    id: '/call-center/voice-templates',
    path: '/call-center/voice-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterSipNumbersRoute =
  AuthenticatedAdminCallCenterSipNumbersRouteImport.update({
    id: '/call-center/sip-numbers',
    path: '/call-center/sip-numbers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterReportsRoute =
  AuthenticatedAdminCallCenterReportsRouteImport.update({
    id: '/call-center/reports',
    path: '/call-center/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterIpPhonesRoute =
  AuthenticatedAdminCallCenterIpPhonesRouteImport.update({
    id: '/call-center/ip-phones',
    path: '/call-center/ip-phones',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterFollowUpsRoute =
  AuthenticatedAdminCallCenterFollowUpsRouteImport.update({
    id: '/call-center/follow-ups',
    path: '/call-center/follow-ups',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterCallLogsRoute =
  AuthenticatedAdminCallCenterCallLogsRouteImport.update({
    id: '/call-center/call-logs',
    path: '/call-center/call-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCallCenterAutoVoiceSmsRoute =
  AuthenticatedAdminCallCenterAutoVoiceSmsRouteImport.update({
    id: '/call-center/auto-voice-sms',
    path: '/call-center/auto-voice-sms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRoute
  '/reseller': typeof AuthenticatedResellerRouteWithChildren
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/address': typeof AuthenticatedAdminAddressRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/olt': typeof AuthenticatedAdminOltRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/reseller/accounts': typeof AuthenticatedResellerAccountsRoute
  '/reseller/accounts-history': typeof AuthenticatedResellerAccountsHistoryRoute
  '/reseller/customer-search': typeof AuthenticatedResellerCustomerSearchRoute
  '/reseller/customers': typeof AuthenticatedResellerCustomersRoute
  '/reseller/packages': typeof AuthenticatedResellerPackagesRoute
  '/reseller/reports': typeof AuthenticatedResellerReportsRoute
  '/reseller/sms': typeof AuthenticatedResellerSmsRoute
  '/reseller/support': typeof AuthenticatedResellerSupportRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/reseller/': typeof AuthenticatedResellerIndexRoute
  '/admin/call-center/auto-voice-sms': typeof AuthenticatedAdminCallCenterAutoVoiceSmsRoute
  '/admin/call-center/call-logs': typeof AuthenticatedAdminCallCenterCallLogsRoute
  '/admin/call-center/follow-ups': typeof AuthenticatedAdminCallCenterFollowUpsRoute
  '/admin/call-center/ip-phones': typeof AuthenticatedAdminCallCenterIpPhonesRoute
  '/admin/call-center/reports': typeof AuthenticatedAdminCallCenterReportsRoute
  '/admin/call-center/sip-numbers': typeof AuthenticatedAdminCallCenterSipNumbersRoute
  '/admin/call-center/voice-templates': typeof AuthenticatedAdminCallCenterVoiceTemplatesRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/hr/advance-salary': typeof AuthenticatedAdminHrAdvanceSalaryRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/hr/reports': typeof AuthenticatedAdminHrReportsRoute
  '/admin/hr/salary-policies': typeof AuthenticatedAdminHrSalaryPoliciesRoute
  '/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/admin/resellers/access': typeof AuthenticatedAdminResellersAccessRoute
  '/admin/resellers/add': typeof AuthenticatedAdminResellersAddRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/admin/call-center/': typeof AuthenticatedAdminCallCenterIndexRoute
  '/admin/hr/': typeof AuthenticatedAdminHrIndexRoute
  '/admin/resellers/': typeof AuthenticatedAdminResellersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/customer': typeof AuthenticatedCustomerRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/address': typeof AuthenticatedAdminAddressRoute
  '/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/olt': typeof AuthenticatedAdminOltRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/reseller/accounts': typeof AuthenticatedResellerAccountsRoute
  '/reseller/accounts-history': typeof AuthenticatedResellerAccountsHistoryRoute
  '/reseller/customer-search': typeof AuthenticatedResellerCustomerSearchRoute
  '/reseller/customers': typeof AuthenticatedResellerCustomersRoute
  '/reseller/packages': typeof AuthenticatedResellerPackagesRoute
  '/reseller/reports': typeof AuthenticatedResellerReportsRoute
  '/reseller/sms': typeof AuthenticatedResellerSmsRoute
  '/reseller/support': typeof AuthenticatedResellerSupportRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/reseller': typeof AuthenticatedResellerIndexRoute
  '/admin/call-center/auto-voice-sms': typeof AuthenticatedAdminCallCenterAutoVoiceSmsRoute
  '/admin/call-center/call-logs': typeof AuthenticatedAdminCallCenterCallLogsRoute
  '/admin/call-center/follow-ups': typeof AuthenticatedAdminCallCenterFollowUpsRoute
  '/admin/call-center/ip-phones': typeof AuthenticatedAdminCallCenterIpPhonesRoute
  '/admin/call-center/reports': typeof AuthenticatedAdminCallCenterReportsRoute
  '/admin/call-center/sip-numbers': typeof AuthenticatedAdminCallCenterSipNumbersRoute
  '/admin/call-center/voice-templates': typeof AuthenticatedAdminCallCenterVoiceTemplatesRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/hr/advance-salary': typeof AuthenticatedAdminHrAdvanceSalaryRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/admin/hr/reports': typeof AuthenticatedAdminHrReportsRoute
  '/admin/hr/salary-policies': typeof AuthenticatedAdminHrSalaryPoliciesRoute
  '/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/admin/resellers/access': typeof AuthenticatedAdminResellersAccessRoute
  '/admin/resellers/add': typeof AuthenticatedAdminResellersAddRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/admin/call-center': typeof AuthenticatedAdminCallCenterIndexRoute
  '/admin/hr': typeof AuthenticatedAdminHrIndexRoute
  '/admin/resellers': typeof AuthenticatedAdminResellersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRoute
  '/_authenticated/reseller': typeof AuthenticatedResellerRouteWithChildren
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/address': typeof AuthenticatedAdminAddressRoute
  '/_authenticated/admin/appearance': typeof AuthenticatedAdminAppearanceRoute
  '/_authenticated/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/olt': typeof AuthenticatedAdminOltRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/_authenticated/reseller/accounts': typeof AuthenticatedResellerAccountsRoute
  '/_authenticated/reseller/accounts-history': typeof AuthenticatedResellerAccountsHistoryRoute
  '/_authenticated/reseller/customer-search': typeof AuthenticatedResellerCustomerSearchRoute
  '/_authenticated/reseller/customers': typeof AuthenticatedResellerCustomersRoute
  '/_authenticated/reseller/packages': typeof AuthenticatedResellerPackagesRoute
  '/_authenticated/reseller/reports': typeof AuthenticatedResellerReportsRoute
  '/_authenticated/reseller/sms': typeof AuthenticatedResellerSmsRoute
  '/_authenticated/reseller/support': typeof AuthenticatedResellerSupportRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/reseller/': typeof AuthenticatedResellerIndexRoute
  '/_authenticated/admin/call-center/auto-voice-sms': typeof AuthenticatedAdminCallCenterAutoVoiceSmsRoute
  '/_authenticated/admin/call-center/call-logs': typeof AuthenticatedAdminCallCenterCallLogsRoute
  '/_authenticated/admin/call-center/follow-ups': typeof AuthenticatedAdminCallCenterFollowUpsRoute
  '/_authenticated/admin/call-center/ip-phones': typeof AuthenticatedAdminCallCenterIpPhonesRoute
  '/_authenticated/admin/call-center/reports': typeof AuthenticatedAdminCallCenterReportsRoute
  '/_authenticated/admin/call-center/sip-numbers': typeof AuthenticatedAdminCallCenterSipNumbersRoute
  '/_authenticated/admin/call-center/voice-templates': typeof AuthenticatedAdminCallCenterVoiceTemplatesRoute
  '/_authenticated/admin/customers_/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/hr/advance-salary': typeof AuthenticatedAdminHrAdvanceSalaryRoute
  '/_authenticated/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/_authenticated/admin/hr/employees': typeof AuthenticatedAdminHrEmployeesRoute
  '/_authenticated/admin/hr/leave': typeof AuthenticatedAdminHrLeaveRoute
  '/_authenticated/admin/hr/payroll': typeof AuthenticatedAdminHrPayrollRoute
  '/_authenticated/admin/hr/reports': typeof AuthenticatedAdminHrReportsRoute
  '/_authenticated/admin/hr/salary-policies': typeof AuthenticatedAdminHrSalaryPoliciesRoute
  '/_authenticated/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/_authenticated/admin/resellers/access': typeof AuthenticatedAdminResellersAccessRoute
  '/_authenticated/admin/resellers/add': typeof AuthenticatedAdminResellersAddRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/_authenticated/admin/call-center/': typeof AuthenticatedAdminCallCenterIndexRoute
  '/_authenticated/admin/hr/': typeof AuthenticatedAdminHrIndexRoute
  '/_authenticated/admin/resellers/': typeof AuthenticatedAdminResellersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/admin'
    | '/customer'
    | '/reseller'
    | '/admin/access'
    | '/admin/accounts'
    | '/admin/address'
    | '/admin/appearance'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/mikrotik'
    | '/admin/notices'
    | '/admin/olt'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/zones'
    | '/reseller/accounts'
    | '/reseller/accounts-history'
    | '/reseller/customer-search'
    | '/reseller/customers'
    | '/reseller/packages'
    | '/reseller/reports'
    | '/reseller/sms'
    | '/reseller/support'
    | '/pay-bill/receipt/$receiptNo'
    | '/admin/'
    | '/reseller/'
    | '/admin/call-center/auto-voice-sms'
    | '/admin/call-center/call-logs'
    | '/admin/call-center/follow-ups'
    | '/admin/call-center/ip-phones'
    | '/admin/call-center/reports'
    | '/admin/call-center/sip-numbers'
    | '/admin/call-center/voice-templates'
    | '/admin/customers/$id'
    | '/admin/hr/advance-salary'
    | '/admin/hr/attendance'
    | '/admin/hr/employees'
    | '/admin/hr/leave'
    | '/admin/hr/payroll'
    | '/admin/hr/reports'
    | '/admin/hr/salary-policies'
    | '/admin/reports/address'
    | '/admin/resellers/access'
    | '/admin/resellers/add'
    | '/api/public/cron/run'
    | '/admin/call-center/'
    | '/admin/hr/'
    | '/admin/resellers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/customer'
    | '/admin/access'
    | '/admin/accounts'
    | '/admin/address'
    | '/admin/appearance'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/mikrotik'
    | '/admin/notices'
    | '/admin/olt'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/zones'
    | '/reseller/accounts'
    | '/reseller/accounts-history'
    | '/reseller/customer-search'
    | '/reseller/customers'
    | '/reseller/packages'
    | '/reseller/reports'
    | '/reseller/sms'
    | '/reseller/support'
    | '/pay-bill/receipt/$receiptNo'
    | '/admin'
    | '/reseller'
    | '/admin/call-center/auto-voice-sms'
    | '/admin/call-center/call-logs'
    | '/admin/call-center/follow-ups'
    | '/admin/call-center/ip-phones'
    | '/admin/call-center/reports'
    | '/admin/call-center/sip-numbers'
    | '/admin/call-center/voice-templates'
    | '/admin/customers/$id'
    | '/admin/hr/advance-salary'
    | '/admin/hr/attendance'
    | '/admin/hr/employees'
    | '/admin/hr/leave'
    | '/admin/hr/payroll'
    | '/admin/hr/reports'
    | '/admin/hr/salary-policies'
    | '/admin/reports/address'
    | '/admin/resellers/access'
    | '/admin/resellers/add'
    | '/api/public/cron/run'
    | '/admin/call-center'
    | '/admin/hr'
    | '/admin/resellers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/reseller'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/address'
    | '/_authenticated/admin/appearance'
    | '/_authenticated/admin/bills'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/mikrotik'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/olt'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/zones'
    | '/_authenticated/reseller/accounts'
    | '/_authenticated/reseller/accounts-history'
    | '/_authenticated/reseller/customer-search'
    | '/_authenticated/reseller/customers'
    | '/_authenticated/reseller/packages'
    | '/_authenticated/reseller/reports'
    | '/_authenticated/reseller/sms'
    | '/_authenticated/reseller/support'
    | '/pay-bill/receipt/$receiptNo'
    | '/_authenticated/admin/'
    | '/_authenticated/reseller/'
    | '/_authenticated/admin/call-center/auto-voice-sms'
    | '/_authenticated/admin/call-center/call-logs'
    | '/_authenticated/admin/call-center/follow-ups'
    | '/_authenticated/admin/call-center/ip-phones'
    | '/_authenticated/admin/call-center/reports'
    | '/_authenticated/admin/call-center/sip-numbers'
    | '/_authenticated/admin/call-center/voice-templates'
    | '/_authenticated/admin/customers_/$id'
    | '/_authenticated/admin/hr/advance-salary'
    | '/_authenticated/admin/hr/attendance'
    | '/_authenticated/admin/hr/employees'
    | '/_authenticated/admin/hr/leave'
    | '/_authenticated/admin/hr/payroll'
    | '/_authenticated/admin/hr/reports'
    | '/_authenticated/admin/hr/salary-policies'
    | '/_authenticated/admin/reports/address'
    | '/_authenticated/admin/resellers/access'
    | '/_authenticated/admin/resellers/add'
    | '/api/public/cron/run'
    | '/_authenticated/admin/call-center/'
    | '/_authenticated/admin/hr/'
    | '/_authenticated/admin/resellers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PayBillRoute: typeof PayBillRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronRunRoute: typeof ApiPublicCronRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bill': {
      id: '/pay-bill'
      path: '/pay-bill'
      fullPath: '/pay-bill'
      preLoaderRoute: typeof PayBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reseller/': {
      id: '/_authenticated/reseller/'
      path: '/'
      fullPath: '/reseller/'
      preLoaderRoute: typeof AuthenticatedResellerIndexRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/pay-bill/receipt/$receiptNo': {
      id: '/pay-bill/receipt/$receiptNo'
      path: '/receipt/$receiptNo'
      fullPath: '/pay-bill/receipt/$receiptNo'
      preLoaderRoute: typeof PayBillReceiptReceiptNoRouteImport
      parentRoute: typeof PayBillRoute
    }
    '/_authenticated/reseller/support': {
      id: '/_authenticated/reseller/support'
      path: '/support'
      fullPath: '/reseller/support'
      preLoaderRoute: typeof AuthenticatedResellerSupportRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/sms': {
      id: '/_authenticated/reseller/sms'
      path: '/sms'
      fullPath: '/reseller/sms'
      preLoaderRoute: typeof AuthenticatedResellerSmsRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/reports': {
      id: '/_authenticated/reseller/reports'
      path: '/reports'
      fullPath: '/reseller/reports'
      preLoaderRoute: typeof AuthenticatedResellerReportsRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/packages': {
      id: '/_authenticated/reseller/packages'
      path: '/packages'
      fullPath: '/reseller/packages'
      preLoaderRoute: typeof AuthenticatedResellerPackagesRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/customers': {
      id: '/_authenticated/reseller/customers'
      path: '/customers'
      fullPath: '/reseller/customers'
      preLoaderRoute: typeof AuthenticatedResellerCustomersRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/customer-search': {
      id: '/_authenticated/reseller/customer-search'
      path: '/customer-search'
      fullPath: '/reseller/customer-search'
      preLoaderRoute: typeof AuthenticatedResellerCustomerSearchRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/accounts-history': {
      id: '/_authenticated/reseller/accounts-history'
      path: '/accounts-history'
      fullPath: '/reseller/accounts-history'
      preLoaderRoute: typeof AuthenticatedResellerAccountsHistoryRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/reseller/accounts': {
      id: '/_authenticated/reseller/accounts'
      path: '/accounts'
      fullPath: '/reseller/accounts'
      preLoaderRoute: typeof AuthenticatedResellerAccountsRouteImport
      parentRoute: typeof AuthenticatedResellerRoute
    }
    '/_authenticated/admin/zones': {
      id: '/_authenticated/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/olt': {
      id: '/_authenticated/admin/olt'
      path: '/olt'
      fullPath: '/admin/olt'
      preLoaderRoute: typeof AuthenticatedAdminOltRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mikrotik': {
      id: '/_authenticated/admin/mikrotik'
      path: '/mikrotik'
      fullPath: '/admin/mikrotik'
      preLoaderRoute: typeof AuthenticatedAdminMikrotikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bills': {
      id: '/_authenticated/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AuthenticatedAdminBillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appearance': {
      id: '/_authenticated/admin/appearance'
      path: '/appearance'
      fullPath: '/admin/appearance'
      preLoaderRoute: typeof AuthenticatedAdminAppearanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/address': {
      id: '/_authenticated/admin/address'
      path: '/address'
      fullPath: '/admin/address'
      preLoaderRoute: typeof AuthenticatedAdminAddressRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resellers/': {
      id: '/_authenticated/admin/resellers/'
      path: '/resellers'
      fullPath: '/admin/resellers/'
      preLoaderRoute: typeof AuthenticatedAdminResellersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/': {
      id: '/_authenticated/admin/hr/'
      path: '/hr'
      fullPath: '/admin/hr/'
      preLoaderRoute: typeof AuthenticatedAdminHrIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/': {
      id: '/_authenticated/admin/call-center/'
      path: '/call-center'
      fullPath: '/admin/call-center/'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/run': {
      id: '/api/public/cron/run'
      path: '/api/public/cron/run'
      fullPath: '/api/public/cron/run'
      preLoaderRoute: typeof ApiPublicCronRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/resellers/add': {
      id: '/_authenticated/admin/resellers/add'
      path: '/resellers/add'
      fullPath: '/admin/resellers/add'
      preLoaderRoute: typeof AuthenticatedAdminResellersAddRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resellers/access': {
      id: '/_authenticated/admin/resellers/access'
      path: '/resellers/access'
      fullPath: '/admin/resellers/access'
      preLoaderRoute: typeof AuthenticatedAdminResellersAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports/address': {
      id: '/_authenticated/admin/reports/address'
      path: '/reports/address'
      fullPath: '/admin/reports/address'
      preLoaderRoute: typeof AuthenticatedAdminReportsAddressRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/salary-policies': {
      id: '/_authenticated/admin/hr/salary-policies'
      path: '/hr/salary-policies'
      fullPath: '/admin/hr/salary-policies'
      preLoaderRoute: typeof AuthenticatedAdminHrSalaryPoliciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/reports': {
      id: '/_authenticated/admin/hr/reports'
      path: '/hr/reports'
      fullPath: '/admin/hr/reports'
      preLoaderRoute: typeof AuthenticatedAdminHrReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/payroll': {
      id: '/_authenticated/admin/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/admin/hr/payroll'
      preLoaderRoute: typeof AuthenticatedAdminHrPayrollRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/leave': {
      id: '/_authenticated/admin/hr/leave'
      path: '/hr/leave'
      fullPath: '/admin/hr/leave'
      preLoaderRoute: typeof AuthenticatedAdminHrLeaveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/employees': {
      id: '/_authenticated/admin/hr/employees'
      path: '/hr/employees'
      fullPath: '/admin/hr/employees'
      preLoaderRoute: typeof AuthenticatedAdminHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/attendance': {
      id: '/_authenticated/admin/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/admin/hr/attendance'
      preLoaderRoute: typeof AuthenticatedAdminHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/advance-salary': {
      id: '/_authenticated/admin/hr/advance-salary'
      path: '/hr/advance-salary'
      fullPath: '/admin/hr/advance-salary'
      preLoaderRoute: typeof AuthenticatedAdminHrAdvanceSalaryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers_/$id': {
      id: '/_authenticated/admin/customers_/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/voice-templates': {
      id: '/_authenticated/admin/call-center/voice-templates'
      path: '/call-center/voice-templates'
      fullPath: '/admin/call-center/voice-templates'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterVoiceTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/sip-numbers': {
      id: '/_authenticated/admin/call-center/sip-numbers'
      path: '/call-center/sip-numbers'
      fullPath: '/admin/call-center/sip-numbers'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterSipNumbersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/reports': {
      id: '/_authenticated/admin/call-center/reports'
      path: '/call-center/reports'
      fullPath: '/admin/call-center/reports'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/ip-phones': {
      id: '/_authenticated/admin/call-center/ip-phones'
      path: '/call-center/ip-phones'
      fullPath: '/admin/call-center/ip-phones'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterIpPhonesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/follow-ups': {
      id: '/_authenticated/admin/call-center/follow-ups'
      path: '/call-center/follow-ups'
      fullPath: '/admin/call-center/follow-ups'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterFollowUpsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/call-logs': {
      id: '/_authenticated/admin/call-center/call-logs'
      path: '/call-center/call-logs'
      fullPath: '/admin/call-center/call-logs'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterCallLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/call-center/auto-voice-sms': {
      id: '/_authenticated/admin/call-center/auto-voice-sms'
      path: '/call-center/auto-voice-sms'
      fullPath: '/admin/call-center/auto-voice-sms'
      preLoaderRoute: typeof AuthenticatedAdminCallCenterAutoVoiceSmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminAddressRoute: typeof AuthenticatedAdminAddressRoute
  AuthenticatedAdminAppearanceRoute: typeof AuthenticatedAdminAppearanceRoute
  AuthenticatedAdminBillsRoute: typeof AuthenticatedAdminBillsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminMikrotikRoute: typeof AuthenticatedAdminMikrotikRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminOltRoute: typeof AuthenticatedAdminOltRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminZonesRoute: typeof AuthenticatedAdminZonesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCallCenterAutoVoiceSmsRoute: typeof AuthenticatedAdminCallCenterAutoVoiceSmsRoute
  AuthenticatedAdminCallCenterCallLogsRoute: typeof AuthenticatedAdminCallCenterCallLogsRoute
  AuthenticatedAdminCallCenterFollowUpsRoute: typeof AuthenticatedAdminCallCenterFollowUpsRoute
  AuthenticatedAdminCallCenterIpPhonesRoute: typeof AuthenticatedAdminCallCenterIpPhonesRoute
  AuthenticatedAdminCallCenterReportsRoute: typeof AuthenticatedAdminCallCenterReportsRoute
  AuthenticatedAdminCallCenterSipNumbersRoute: typeof AuthenticatedAdminCallCenterSipNumbersRoute
  AuthenticatedAdminCallCenterVoiceTemplatesRoute: typeof AuthenticatedAdminCallCenterVoiceTemplatesRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminHrAdvanceSalaryRoute: typeof AuthenticatedAdminHrAdvanceSalaryRoute
  AuthenticatedAdminHrAttendanceRoute: typeof AuthenticatedAdminHrAttendanceRoute
  AuthenticatedAdminHrEmployeesRoute: typeof AuthenticatedAdminHrEmployeesRoute
  AuthenticatedAdminHrLeaveRoute: typeof AuthenticatedAdminHrLeaveRoute
  AuthenticatedAdminHrPayrollRoute: typeof AuthenticatedAdminHrPayrollRoute
  AuthenticatedAdminHrReportsRoute: typeof AuthenticatedAdminHrReportsRoute
  AuthenticatedAdminHrSalaryPoliciesRoute: typeof AuthenticatedAdminHrSalaryPoliciesRoute
  AuthenticatedAdminReportsAddressRoute: typeof AuthenticatedAdminReportsAddressRoute
  AuthenticatedAdminResellersAccessRoute: typeof AuthenticatedAdminResellersAccessRoute
  AuthenticatedAdminResellersAddRoute: typeof AuthenticatedAdminResellersAddRoute
  AuthenticatedAdminCallCenterIndexRoute: typeof AuthenticatedAdminCallCenterIndexRoute
  AuthenticatedAdminHrIndexRoute: typeof AuthenticatedAdminHrIndexRoute
  AuthenticatedAdminResellersIndexRoute: typeof AuthenticatedAdminResellersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminAddressRoute: AuthenticatedAdminAddressRoute,
  AuthenticatedAdminAppearanceRoute: AuthenticatedAdminAppearanceRoute,
  AuthenticatedAdminBillsRoute: AuthenticatedAdminBillsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminMikrotikRoute: AuthenticatedAdminMikrotikRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminOltRoute: AuthenticatedAdminOltRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminZonesRoute: AuthenticatedAdminZonesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCallCenterAutoVoiceSmsRoute:
    AuthenticatedAdminCallCenterAutoVoiceSmsRoute,
  AuthenticatedAdminCallCenterCallLogsRoute:
    AuthenticatedAdminCallCenterCallLogsRoute,
  AuthenticatedAdminCallCenterFollowUpsRoute:
    AuthenticatedAdminCallCenterFollowUpsRoute,
  AuthenticatedAdminCallCenterIpPhonesRoute:
    AuthenticatedAdminCallCenterIpPhonesRoute,
  AuthenticatedAdminCallCenterReportsRoute:
    AuthenticatedAdminCallCenterReportsRoute,
  AuthenticatedAdminCallCenterSipNumbersRoute:
    AuthenticatedAdminCallCenterSipNumbersRoute,
  AuthenticatedAdminCallCenterVoiceTemplatesRoute:
    AuthenticatedAdminCallCenterVoiceTemplatesRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminHrAdvanceSalaryRoute:
    AuthenticatedAdminHrAdvanceSalaryRoute,
  AuthenticatedAdminHrAttendanceRoute: AuthenticatedAdminHrAttendanceRoute,
  AuthenticatedAdminHrEmployeesRoute: AuthenticatedAdminHrEmployeesRoute,
  AuthenticatedAdminHrLeaveRoute: AuthenticatedAdminHrLeaveRoute,
  AuthenticatedAdminHrPayrollRoute: AuthenticatedAdminHrPayrollRoute,
  AuthenticatedAdminHrReportsRoute: AuthenticatedAdminHrReportsRoute,
  AuthenticatedAdminHrSalaryPoliciesRoute:
    AuthenticatedAdminHrSalaryPoliciesRoute,
  AuthenticatedAdminReportsAddressRoute: AuthenticatedAdminReportsAddressRoute,
  AuthenticatedAdminResellersAccessRoute:
    AuthenticatedAdminResellersAccessRoute,
  AuthenticatedAdminResellersAddRoute: AuthenticatedAdminResellersAddRoute,
  AuthenticatedAdminCallCenterIndexRoute:
    AuthenticatedAdminCallCenterIndexRoute,
  AuthenticatedAdminHrIndexRoute: AuthenticatedAdminHrIndexRoute,
  AuthenticatedAdminResellersIndexRoute: AuthenticatedAdminResellersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedResellerRouteChildren {
  AuthenticatedResellerAccountsRoute: typeof AuthenticatedResellerAccountsRoute
  AuthenticatedResellerAccountsHistoryRoute: typeof AuthenticatedResellerAccountsHistoryRoute
  AuthenticatedResellerCustomerSearchRoute: typeof AuthenticatedResellerCustomerSearchRoute
  AuthenticatedResellerCustomersRoute: typeof AuthenticatedResellerCustomersRoute
  AuthenticatedResellerPackagesRoute: typeof AuthenticatedResellerPackagesRoute
  AuthenticatedResellerReportsRoute: typeof AuthenticatedResellerReportsRoute
  AuthenticatedResellerSmsRoute: typeof AuthenticatedResellerSmsRoute
  AuthenticatedResellerSupportRoute: typeof AuthenticatedResellerSupportRoute
  AuthenticatedResellerIndexRoute: typeof AuthenticatedResellerIndexRoute
}

const AuthenticatedResellerRouteChildren: AuthenticatedResellerRouteChildren = {
  AuthenticatedResellerAccountsRoute: AuthenticatedResellerAccountsRoute,
  AuthenticatedResellerAccountsHistoryRoute:
    AuthenticatedResellerAccountsHistoryRoute,
  AuthenticatedResellerCustomerSearchRoute:
    AuthenticatedResellerCustomerSearchRoute,
  AuthenticatedResellerCustomersRoute: AuthenticatedResellerCustomersRoute,
  AuthenticatedResellerPackagesRoute: AuthenticatedResellerPackagesRoute,
  AuthenticatedResellerReportsRoute: AuthenticatedResellerReportsRoute,
  AuthenticatedResellerSmsRoute: AuthenticatedResellerSmsRoute,
  AuthenticatedResellerSupportRoute: AuthenticatedResellerSupportRoute,
  AuthenticatedResellerIndexRoute: AuthenticatedResellerIndexRoute,
}

const AuthenticatedResellerRouteWithChildren =
  AuthenticatedResellerRoute._addFileChildren(
    AuthenticatedResellerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRoute
  AuthenticatedResellerRoute: typeof AuthenticatedResellerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRoute,
  AuthenticatedResellerRoute: AuthenticatedResellerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PayBillRouteChildren {
  PayBillReceiptReceiptNoRoute: typeof PayBillReceiptReceiptNoRoute
}

const PayBillRouteChildren: PayBillRouteChildren = {
  PayBillReceiptReceiptNoRoute: PayBillReceiptReceiptNoRoute,
}

const PayBillRouteWithChildren =
  PayBillRoute._addFileChildren(PayBillRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PayBillRoute: PayBillRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronRunRoute: ApiPublicCronRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
