/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PayBillRouteImport } from './routes/pay-bill'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated.customer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as PayBillReceiptReceiptNoRouteImport } from './routes/pay-bill.receipt.$receiptNo'
import { Route as AuthenticatedAdminZonesRouteImport } from './routes/_authenticated.admin.zones'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated.admin.users'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated.admin.tickets'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated.admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated.admin.payments'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated.admin.packages'
import { Route as AuthenticatedAdminOltRouteImport } from './routes/_authenticated.admin.olt'
import { Route as AuthenticatedAdminNoticesRouteImport } from './routes/_authenticated.admin.notices'
import { Route as AuthenticatedAdminMikrotikRouteImport } from './routes/_authenticated.admin.mikrotik'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated.admin.customers'
import { Route as AuthenticatedAdminBillsRouteImport } from './routes/_authenticated.admin.bills'
import { Route as AuthenticatedAdminAddressRouteImport } from './routes/_authenticated.admin.address'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated.admin.accounts'
import { Route as AuthenticatedAdminErpIndexRouteImport } from './routes/_authenticated.admin.erp.index'
import { Route as ApiPublicCronRunRouteImport } from './routes/api/public/cron/run'
import { Route as AuthenticatedAdminReportsAddressRouteImport } from './routes/_authenticated.admin.reports.address'
import { Route as AuthenticatedAdminHrLeavesRouteImport } from './routes/_authenticated.admin.hr.leaves'
import { Route as AuthenticatedAdminHrAttendanceRouteImport } from './routes/_authenticated.admin.hr.attendance'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated.admin.customers_.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBillRoute = PayBillRouteImport.update({
  id: '/pay-bill',
  path: '/pay-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PayBillReceiptReceiptNoRoute = PayBillReceiptReceiptNoRouteImport.update({
  id: '/receipt/$receiptNo',
  path: '/receipt/$receiptNo',
  getParentRoute: () => PayBillRoute,
} as any)
const AuthenticatedAdminZonesRoute = AuthenticatedAdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOltRoute = AuthenticatedAdminOltRouteImport.update({
  id: '/olt',
  path: '/olt',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNoticesRoute =
  AuthenticatedAdminNoticesRouteImport.update({
    id: '/notices',
    path: '/notices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMikrotikRoute =
  AuthenticatedAdminMikrotikRouteImport.update({
    id: '/mikrotik',
    path: '/mikrotik',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillsRoute = AuthenticatedAdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAddressRoute =
  AuthenticatedAdminAddressRouteImport.update({
    id: '/address',
    path: '/address',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminErpIndexRoute =
  AuthenticatedAdminErpIndexRouteImport.update({
    id: '/erp/',
    path: '/erp/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCronRunRoute = ApiPublicCronRunRouteImport.update({
  id: '/api/public/cron/run',
  path: '/api/public/cron/run',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminReportsAddressRoute =
  AuthenticatedAdminReportsAddressRouteImport.update({
    id: '/reports/address',
    path: '/reports/address',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrLeavesRoute =
  AuthenticatedAdminHrLeavesRouteImport.update({
    id: '/hr/leaves',
    path: '/hr/leaves',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHrAttendanceRoute =
  AuthenticatedAdminHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/customers_/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/customer': typeof AuthenticatedCustomerRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/address': typeof AuthenticatedAdminAddressRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/olt': typeof AuthenticatedAdminOltRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/admin/erp/': typeof AuthenticatedAdminErpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/customer': typeof AuthenticatedCustomerRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/address': typeof AuthenticatedAdminAddressRoute
  '/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/admin/olt': typeof AuthenticatedAdminOltRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/admin/erp': typeof AuthenticatedAdminErpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pay-bill': typeof PayBillRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/customer': typeof AuthenticatedCustomerRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/address': typeof AuthenticatedAdminAddressRoute
  '/_authenticated/admin/bills': typeof AuthenticatedAdminBillsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/mikrotik': typeof AuthenticatedAdminMikrotikRoute
  '/_authenticated/admin/notices': typeof AuthenticatedAdminNoticesRoute
  '/_authenticated/admin/olt': typeof AuthenticatedAdminOltRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/zones': typeof AuthenticatedAdminZonesRoute
  '/pay-bill/receipt/$receiptNo': typeof PayBillReceiptReceiptNoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/customers_/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/hr/attendance': typeof AuthenticatedAdminHrAttendanceRoute
  '/_authenticated/admin/hr/leaves': typeof AuthenticatedAdminHrLeavesRoute
  '/_authenticated/admin/reports/address': typeof AuthenticatedAdminReportsAddressRoute
  '/api/public/cron/run': typeof ApiPublicCronRunRoute
  '/_authenticated/admin/erp/': typeof AuthenticatedAdminErpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/admin'
    | '/customer'
    | '/admin/accounts'
    | '/admin/address'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/mikrotik'
    | '/admin/notices'
    | '/admin/olt'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/zones'
    | '/pay-bill/receipt/$receiptNo'
    | '/admin/'
    | '/admin/customers/$id'
    | '/admin/hr/attendance'
    | '/admin/hr/leaves'
    | '/admin/reports/address'
    | '/api/public/cron/run'
    | '/admin/erp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/customer'
    | '/admin/accounts'
    | '/admin/address'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/mikrotik'
    | '/admin/notices'
    | '/admin/olt'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tickets'
    | '/admin/users'
    | '/admin/zones'
    | '/pay-bill/receipt/$receiptNo'
    | '/admin'
    | '/admin/customers/$id'
    | '/admin/hr/attendance'
    | '/admin/hr/leaves'
    | '/admin/reports/address'
    | '/api/public/cron/run'
    | '/admin/erp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pay-bill'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/customer'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/address'
    | '/_authenticated/admin/bills'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/mikrotik'
    | '/_authenticated/admin/notices'
    | '/_authenticated/admin/olt'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/zones'
    | '/pay-bill/receipt/$receiptNo'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/customers_/$id'
    | '/_authenticated/admin/hr/attendance'
    | '/_authenticated/admin/hr/leaves'
    | '/_authenticated/admin/reports/address'
    | '/api/public/cron/run'
    | '/_authenticated/admin/erp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PayBillRoute: typeof PayBillRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronRunRoute: typeof ApiPublicCronRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-bill': {
      id: '/pay-bill'
      path: '/pay-bill'
      fullPath: '/pay-bill'
      preLoaderRoute: typeof PayBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customer': {
      id: '/_authenticated/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/pay-bill/receipt/$receiptNo': {
      id: '/pay-bill/receipt/$receiptNo'
      path: '/receipt/$receiptNo'
      fullPath: '/pay-bill/receipt/$receiptNo'
      preLoaderRoute: typeof PayBillReceiptReceiptNoRouteImport
      parentRoute: typeof PayBillRoute
    }
    '/_authenticated/admin/zones': {
      id: '/_authenticated/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AuthenticatedAdminZonesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/olt': {
      id: '/_authenticated/admin/olt'
      path: '/olt'
      fullPath: '/admin/olt'
      preLoaderRoute: typeof AuthenticatedAdminOltRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notices': {
      id: '/_authenticated/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AuthenticatedAdminNoticesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mikrotik': {
      id: '/_authenticated/admin/mikrotik'
      path: '/mikrotik'
      fullPath: '/admin/mikrotik'
      preLoaderRoute: typeof AuthenticatedAdminMikrotikRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bills': {
      id: '/_authenticated/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AuthenticatedAdminBillsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/address': {
      id: '/_authenticated/admin/address'
      path: '/address'
      fullPath: '/admin/address'
      preLoaderRoute: typeof AuthenticatedAdminAddressRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/erp/': {
      id: '/_authenticated/admin/erp/'
      path: '/erp'
      fullPath: '/admin/erp/'
      preLoaderRoute: typeof AuthenticatedAdminErpIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cron/run': {
      id: '/api/public/cron/run'
      path: '/api/public/cron/run'
      fullPath: '/api/public/cron/run'
      preLoaderRoute: typeof ApiPublicCronRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/reports/address': {
      id: '/_authenticated/admin/reports/address'
      path: '/reports/address'
      fullPath: '/admin/reports/address'
      preLoaderRoute: typeof AuthenticatedAdminReportsAddressRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/leaves': {
      id: '/_authenticated/admin/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/admin/hr/leaves'
      preLoaderRoute: typeof AuthenticatedAdminHrLeavesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hr/attendance': {
      id: '/_authenticated/admin/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/admin/hr/attendance'
      preLoaderRoute: typeof AuthenticatedAdminHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers_/$id': {
      id: '/_authenticated/admin/customers_/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminAddressRoute: typeof AuthenticatedAdminAddressRoute
  AuthenticatedAdminBillsRoute: typeof AuthenticatedAdminBillsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminMikrotikRoute: typeof AuthenticatedAdminMikrotikRoute
  AuthenticatedAdminNoticesRoute: typeof AuthenticatedAdminNoticesRoute
  AuthenticatedAdminOltRoute: typeof AuthenticatedAdminOltRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminZonesRoute: typeof AuthenticatedAdminZonesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
  AuthenticatedAdminHrAttendanceRoute: typeof AuthenticatedAdminHrAttendanceRoute
  AuthenticatedAdminHrLeavesRoute: typeof AuthenticatedAdminHrLeavesRoute
  AuthenticatedAdminReportsAddressRoute: typeof AuthenticatedAdminReportsAddressRoute
  AuthenticatedAdminErpIndexRoute: typeof AuthenticatedAdminErpIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminAddressRoute: AuthenticatedAdminAddressRoute,
  AuthenticatedAdminBillsRoute: AuthenticatedAdminBillsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminMikrotikRoute: AuthenticatedAdminMikrotikRoute,
  AuthenticatedAdminNoticesRoute: AuthenticatedAdminNoticesRoute,
  AuthenticatedAdminOltRoute: AuthenticatedAdminOltRoute,
  AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminZonesRoute: AuthenticatedAdminZonesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  AuthenticatedAdminHrAttendanceRoute: AuthenticatedAdminHrAttendanceRoute,
  AuthenticatedAdminHrLeavesRoute: AuthenticatedAdminHrLeavesRoute,
  AuthenticatedAdminReportsAddressRoute: AuthenticatedAdminReportsAddressRoute,
  AuthenticatedAdminErpIndexRoute: AuthenticatedAdminErpIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PayBillRouteChildren {
  PayBillReceiptReceiptNoRoute: typeof PayBillReceiptReceiptNoRoute
}

const PayBillRouteChildren: PayBillRouteChildren = {
  PayBillReceiptReceiptNoRoute: PayBillReceiptReceiptNoRoute,
}

const PayBillRouteWithChildren =
  PayBillRoute._addFileChildren(PayBillRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PayBillRoute: PayBillRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronRunRoute: ApiPublicCronRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
