// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnrjnklnmdskhfdiywcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucmpua2xubWRza2hmZGl5d2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MDg3NDEsImV4cCI6MjA5OTQ4NDc0MX0.DjxTjRDRbSCz0iinhBkRtkROxn7BGA7OKzvoaw0uKmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});